### PR TITLE
Fix dialog with include fragment

### LINKED ISSUE #38: Dialog with include-fragment is not working
If I go to the [examples page](https://github.github.io/details-dialog-element/index.html) and click the `dialog with <include-fragment>` it is not loading `content.html`, I have tried in both Chrome and FF. 

The reason why it is not working is that the `attributeChangedCallback` is called before `connectedCallback`, this results in a early return in `attributeChangedCallback` because the element is not yet connected and therefore the parentNode of the details-dialog element is NULL. Because of this the events that call `loadIncludeFragment` are never added.

I don't know if this is the desired callback lifecycle of custom elements, as this is the first time I've dived into them. To be honest it seems weird that the `attributeChangedCallback` is called at all, when no attributes have changed. I would have expected only the `connectedCallback` to be called when the elements are inserted into the DOM and then `attributeChangedCallback` to be called when attributes are changed. 

I can make a PR that solves the issue. I would extract the body of `attributeChangedCallback` into a function and then call that function in both `attributeChangedCallback` and `connectedCallback`. Please let me know what you think.

### PR DESCRIPTION
**Pull request by bnjamin**
fixes #38 

The order of connectedCallback and attributesChangedCallback is not guaranteed, so the event listeners for include fragment has to be added in the connectedCallback as well.

Also the event listeners will be removed in the disconnectedCallback.

### CODE REVIEW

**Comment by koddsson** [comment]
>The order of connectedCallback and attributesChangedCallback is not guaranteed

Do you have references for this? I'm not challenging you on it but would just love to read it and reference it myself in the future.

**Comment by bnjamin** [comment]
TBH no. I found someone else making the claim here https://github.com/WebReflection/document-register-element/issues/119. 

I've read the [spec for custom element reactions](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-reactions) a couple of times now and there doesn't seem to be any order defined.

Maybe it would have been better for `DetailsDialogElement` to extend `HTMLDetailsElement` instead of `HTMLElement`, this way the element would have been self contained and would not have to add event listeners to its parentElement. Then the html would look like this:

```html
  <details-dialog src="/robots" preload>
    <summary>Robots</summary>
    <include-fragment>Loading…</include-fragment>
  </details-dialog>
```

However this may have other drawbacks.

**Comment by muan** [comment]
> I've read the [spec for custom element reactions](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-reactions) a couple of times now and there doesn't seem to be any order defined.

The order is defined [in the upgrade process](https://html.spec.whatwg.org/multipage/custom-elements.html#upgrades). See step 4 for `attributeChangedCallback`, step 5 for `connectedCallback`.

This issue happens because in `attributeChangedCallback` we do not have access to the `parentElement` (`<details>`) yet, and that is because the element has not been fully parsed.

I've made a demo page here: https://html-is.glitch.me/attribute-changed.html See console. In Chrome and Safari the third console statement will have a `null`, but in Safari you get `<body>`.

Thanks for reporting and sending the PR. I'll review the fix perhaps tomorrow.

**Comment by bnjamin** [comment]
I see, thanks for the explanation! 👍

**Comment by muan** [comment]
I created test case for this: https://github.com/github/details-dialog-element/compare/src-preload-test

**Comment by bnjamin** [comment]
Nice, would you like me to add them to my PR?

**Comment by muan** [comment]
> Nice, would you like me to add them to my PR?

Yes please.

**Comment by bnjamin** [comment]
Done

**Pull request merged**
